[project]
name = "marlsat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "pyqt5>=5.15.11",
    "scipy>=1.17.0",
    "scipy-stubs~=1.17.0",
]
